apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-rc
spec:
  replicas: 3
  selector:
    app: mytom
  template:
    metadata:
      labels:
        app: mytom
        ver: "1.0"
    spec:
      containers:
      - name: tomcat-pod
        image: tomcat:8.0
        ports:
        - containerPort: 8080
